services:
  order-service:
    build: ./back/order-service
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
    restart: on-failure

  notification-service:
    build: ./back/notification-service
    container_name: notification-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
    restart: on-failure

  logistics-front:
    build: ./front
    container_name: logistics-front
    ports:
      - "80:80"
    depends_on:
      - order-service
      - notification-service
    restart: on-failure
